name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Leiningen
        run: |
          sudo apt-get install -y leiningen
          lein version
      - name: Test
        run: lein test
